### ISSUE TITLE
Logout from shiny application (not from shiny navbar )

### ISSUE THREAD

**Issue by evfonarik** [openanalytics/shinyproxy#112]
Hi team, 
Mine shiny app has an logout button thats configured same as signout button in navbar (https://github.com/openanalytics/shinyproxy/blob/95308b1eb49b84087ccb7704c27b6707006d1407/src/main/resources/fragments/navbar.html#L40)
Button in NavBar works fine, but logout from application browser does not redirect and throws the following:
```
Error in browser console:
`Mixed Content: The page at 'https://domain_name/app/app_name' was loaded over HTTPS, but requested an insecure resource 'http://domain_name/login'. This request has been blocked; the content must be served over HTTPS.`
```

On 2.0.1 shinyproxy redirects to http://domain/login
On 2.0.2 and 2.0.5 redirects to http://domain/
Nginx is configured based on https://www.shinyproxy.io/security/
Shinyproxy is configured for keycloak authentication - login is working.

Could you please show possible way to logout from application directly (not from shiny navbar ), or confirm that its not the best way to do so. @fmichielssen
Thank you!

**Comment by michaelhogersosis** [comment]
Hi evfonarik, 

Are you using the navigation bar at all in your application? You could consider using /app_direct/app_name/ instead of /app/app_name to open the application. The /app/app_name launches the R Shiny application in an iframe, HTTPS prohibits a user from opening the logout link inside the iframe. Using /app_direct/app_name/ you should be able to use the logout link without the error you reported. 

Best regards,

Michael

**Comment by LEDfan** [comment]
Hi have a look at https://github.com/openanalytics/shinyproxy/issues/257#issuecomment-749400781 which should give you a way to logout from the app.
