### ISSUE TITLE
Is it possible to preload packages R used in shiny apps?

### ISSUE THREAD

**Issue by PauloJhonny** [openanalytics/shinyproxy#197]
Hello.

I'm using docker-compose for shinyproxy and I have two shiny apps deployed. I would like to know if is it possible to preload packages R that are used in this apps? 

Could I put a _Rprofile_ script in the Dockerfile of the each app container-image to load the packages/data in memory when it starts? That way the packages will be ready to use when requests come in. (something like the openCPU API).

Thank you.

**Comment by shrektan** [comment]
I don't really know what you mean by "preload packages". I think your app needs to load some data and it takes time. Shinyproxy will launch a container for each user so it means the user needs to wait for a while. 

You don't want the user to wait. Correct?

No, there' s no direct way because it's different from how openCPU works. 

However, there're always workarounds:

1. Make a plumber API hosted in your docker-compose and fetch the plumber API to handle the heavy data load;
1. If you only have limited users, you could use an Nginx proxy image, which directs all the traffic to a shiny app hosted by docker-compose. In other words, you just use Shinyproxy to handle the auth and security stuff. The shiny app is handled separately.

**Comment by PauloJhonny** [comment]
Hi, @shrektan.

Thank you for your suggestions. I will try to do the same thing that you proposed in 1 using the openCPU API, which is already in production.

I hope It will work well.

**Comment by tdeenes** [comment]
> I don't really know what you mean by "preload packages". I think your app needs to load some data and it takes time. Shinyproxy will launch a container for each user so it means the user needs to wait for a while.
> 
> You don't want the user to wait. Correct?
> 
> No, there' s no direct way because it's different from how openCPU works.
> 
> However, there're always workarounds:
> 
> 1. Make a plumber API hosted in your docker-compose and fetch the plumber API to handle the heavy data load;
> 2. If you only have limited users, you could use an Nginx proxy image, which directs all the traffic to a shiny app hosted by docker-compose. In other words, you just use Shinyproxy to handle the auth and security stuff. The shiny app is handled separately.
> 
> I personally use both two workarounds and it works great for me.

@shrektan , can you please elaborate on the 2nd workaround? Or maybe point to a github-repo with a minimal example?

**Comment by shrektan** [comment]
@tdeenes OK, I've updated this method in https://github.com/shrektan/shinyproxy-docker-compose-example. Please take a look.

**Comment by tdeenes** [comment]
@shrektan , thanks!

**Comment by obenno** [comment]
Hi,

I'm also interested in the topic. Is there a way to make shinyproxy pre-load some containers for the app waiting for user connection?

Thanks,
obenno
