### ISSUE TITLE
shinyproxy failed to start when using port 88

### ISSUE THREAD

**Issue by adanba** [openanalytics/shinyproxy#199]
Hello,
when i use the port 88 to start shinyproxy, this failed because the port is already in use by an other service of spring environment.
Can you please add to documentation a caution or warning about the use of this port (88)?
Info : 
- shinyproxy-2.3.0.jar

![image](https://user-images.githubusercontent.com/10264934/79571117-ef94cc00-80ba-11ea-9c5f-bfa71f1c8087.png)

**Comment by LEDfan** [comment]
Hi

Thanks for opening an issue.  Port 88 is used by (among others) KDC.
However, it is always possible that a specific port is already used on your system. That would mean we would have to add warning to the docs for every port that exists. I think that the error report in the logs should be clear enough for the user, so that they can change their configuration.
