### ISSUE TITLE
Create and manage groups in shinyproxy (LDAP authentication)

### ISSUE THREAD

**Issue by PauloJhonny** [openanalytics/shinyproxy#207]
Hi,

I configured shinyproxy with LDAP authentication on a server using docker-compose. It turns out that the sector that manages the ldap service is not the same as mine. Therefore, only this other sector can create and manage groups in LDAP. That way, they are not allowed to create groups for me because they believe this must be in the application.

Is it possible to create and manage groups in shinyproxy itself using LDAP just to authenticate? I would like to create a group called 'admins' to include my user as an administrator of the apps. However, I don't know where to start. I evaluated whether I would have to fiddle with the navbar.html or index.html file, but I'm not sure what exactly I have to do to create this group.

Could anybody help me? Unfortunately, people in the other sector are not allowed to create and manage LDAP groups in my case. So I need to use LDAP only to authenticate and I must create the groups in the application itself.

Thank you.

**Comment by LEDfan** [comment]
Hi

With ShinyProxy it's currently not possible to create groups on top of LDAP authentication. However, since ShinyProxy 2.6.0 it's possible to specify a list of users that are allowed to access an app. In essence, I think this is what you need. Your users authenticate via LDAP and you can specify for each app which users can access it. 

See https://shinyproxy.io/documentation/configuration/#access-users

**Comment by PauloJhonny** [comment]
Hi, @LEDfan. I’m using the access-users functionality to do so. Thanks for your help.

**Comment by LEDfan** [comment]
Great! Thanks for reporting back. Since then I believe your issue is solved, I'm going to close this issue.
