### ISSUE TITLE
Socket client disconnect

### ISSUE THREAD

**Issue by mikiril** [openanalytics/shinyproxy#230]
Hi guys,

There seems to be no websocket reconnect mechanism implemented and the hearbeat interval is not respected here.
To reproduce on Mac please start your app, wait until it is loaded and turn WiFi off for a second. Client greys out and the following is found in the console:

WebSocket network error: The operation couldn’t be completed. Socket is not connected
TypeError: null is not an object (evaluating ‘this.$socket.readyState’)
![E326A194-6F01-4BDD-BAFD-C60467A5E6EB](https://user-images.githubusercontent.com/48929179/93024321-eec67e80-f5f5-11ea-8f8d-3a99dd5a410e.png)

I was wondering if there are settings to workaround this? If not, is it possible to introduce a time out setting for websocket connection or implement a reconnect mechanism?
This would be very useful, for example, when running on mobile where websocket connection is closed when the phone is locked.

The issue was also submitted as a question on 
[openanalytics forum](https://support.openanalytics.eu/t/socket-client-reconnect/1701) 

Many thanks!

**Comment by mikiril** [comment]
Hi again,

I ended up implementing a workaround using  session$allowReconnect.
But still, it would be great if this was fixed on shinyproxy side.

**Comment by tverbeke** [comment]
Thanks for the detailed report, @mikiril

**Comment by LEDfan** [comment]
Hi @mikiril 

Automatically reconnecting the websocket connection is part of [ShinyProxy 2.6.0](https://shinyproxy.io/downloads/#260) (ContainerProxy 0.8.10) which we just released.

Note that this isn't a magic feature: your R Shiny app still has to support the reconnecting mechanism, but it can now be controlled from within ShinyProxy. See our docs for more information: https://shinyproxy.io/documentation/ui/#automatically-reconnecting-websockets
Since this is quite a complex feature with many little details, I'm looking forward to your experience with it. Don't hesitate to report any positive or negative experience with it, thanks :)
