### ISSUE TITLE
app code on github

### ISSUE THREAD

**Issue by gazetapl** [openanalytics/shinyproxy#236]
I want to keep my application code on git repo. Is it possible to sync/clone app from repo when app is starting in shinyproxy? I could download it to container before container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"] but i don't know how and where do the sync.

**Comment by Dusan-Dingarac** [comment]
Hi Gazetapl,  
option 1: you should create one folder on computer where is ShinyProxy (eg. /root/myapp) and sync app code from git in it. Prepare needed files for creating container, and create it after each sync with git.
option 2: prepare container with your app directly form git (after code push) - CI/CD and place it in container registry (both CI/CD and container registry you can build with GitLab). Tell ShinyProxy to use container from container registry (container-image field in applicatiom.yml). You can use also some public container registry as dockers one instead of your private, if this is ok for you.

**Comment by LEDfan** [comment]
Hi @gazetapl 

As I believe that your question is answered, I'm closing this issue. Feel free to re-open it if you need more help.
