### ISSUE TITLE
SHINYPROXY_USERGROUPS empty with Kerberos

### ISSUE THREAD

**Issue by micheljung** [openanalytics/shinyproxy#242]
According to (the documentation)[https://www.shinyproxy.io/configuration/#environment-variables_1]:

> When a user is authenticated, the following environment variables will be available in any Shiny application launched by the user:
> * SHINYPROXY_USERNAME: the name of the user, as used when logging in;
> * SHINYPROXY_USERGROUPS: the groups the authenticated user is a member of, as a comma-separated value.

It sounds very generic but is actually under `Kerberos`. However, in my case, `SHINYPROXY_USERGROUPS` is empty.
From what I know about Kerberos, it doesn't contain any group information so it needs to be looked up via LDAP. The corresponding properties `user-dn-pattern`, `group-search-filter`, and `group-search-base` are (according to the documentation) only for LDAP authentication.

How is it meant to work with Kerberos?

**Comment by Dusan-Dingarac** [comment]
Hi Michel,,

I am not sure exactly how you use Keycloak (eg. if you connect it with some external identity provider), but if you add user to some previously created group under realm, SHINYPROXY_USERGROUPS will return you comma-separated list of all groups in which user is member.
I've just checked it.

**Comment by micheljung** [comment]
Hi Dusan,

We don't use Keycloak, we use Kerberos with Active Directory.

**Comment by filpro** [comment]
Hi @micheljung 
Have you managed to find the solution?

**Comment by micheljung** [comment]
Hi @filpro 
Unfortunately not, for now we continue without Kerberos.

@Dusan-Dingarac could you respond to my initial question?

**Comment by Dusan-Dingarac** [comment]
Hi Michel,

my idea was to use Keycloak with Shinyproxy and to try to connect Kerberos as Identity provider for Keycloak... But, I think that you are right that group are part of LDAP not Kerberos itself....
But, you mentioned that you are using AD (which is in kind of Kerberos + LDAP combination). With one command you can start Keycloak docker container (you need some database also) and try to configure Keycloak Identity provider OIDC to your AD. I did not tried that but I saw in searches some blogs about that.
I hope that this can be solution for you and @filpro

**Comment by LEDfan** [comment]
Hi, we have removed support for Kerberos in ShinyProxy 3.0.0. The reason is that we lack the time and resources to fully support Kerberos in a high-quality way. We don't have any test servers or test documentation, and since Kerberos is such a complex system and also contains many proprietary implementations it's also hard to set up such test servers. Furthermore, we see that the adoption of Kerberos in ShinyProxy is very low. We have a few customers using Kerberos, but they always integrate Kerberos with their IDP and then integrate ShinyProxy with the IDP (e.g. using openid or saml). This is the same method as suggested by @Dusan-Dingarac .
