### ISSUE TITLE
Get roles from OIDC authentication

### ISSUE THREAD

**Issue by erossini** [openanalytics/shinyproxy#275]
I'm trying to connect ShinyProxy with the IdentityServer. How can I read the roles? How can I configure the `application.yml`?

**Comment by LEDfan** [comment]
You'll have to configure IdentityServer so that it adds a custom claim to the ID token, which contains an array of roles.
See our documentation on this: https://shinyproxy.io/documentation/configuration/po_index/#group-based-authorization
Then you can add the name of this claim to the ShinyProxy configuration:
```
proxy:
  openid:
    roles-claim: <claim_name>
```

I don't have experience with IdentityServer, so I cannot tell you exactly how to do it. Please consult the official documentation. Thanks.

**Comment by erossini-chi** [comment]
After a lot of research and study, I found how to implement `Identity Server` with ShinyProxy. I have created a complete step-by-step guide in [my blog](https://www.puresourcecode.com/programming-languages/r/authentication-in-shinyproxy-with-identityserver/). 

I hope it could help other guys.

**Comment by LEDfan** [comment]
Hi @erossini-chi 

Many thanks for your efforts and for clearly documenting your setup! I'm sure it will help other users when they need to set ShinyProxy with IdentityServer.

I'm closing this issue now, but feel free to open a new issue if you encounter any issue.
