### ISSUE TITLE
Shinyproxy with Flask App Prefix Issue

### ISSUE THREAD

**Issue by NealXie** [openanalytics/shinyproxy#279]
I have built a Flask app with some templates and static files like css, js, local csv, db, etc. And then I create a docker image for this app.

I also put this app image into my application.yml file for my shinyproxy. My shinyproxy can load my landing page without css, js, or other files because they are in different url. My Flask is looking for url_for 'statics' but the proxy can't find it. 

I think Dash has a solution to config prefix so the shinyproxy can read it but how about Flask app.

Please let me know if you need more information.

**Comment by decat7** [comment]
Hi,

My colleague solved this issue with workaround in flask. See https://flask-assets.readthedocs.io/en/latest/

**Comment by LEDfan** [comment]
Recently I had to setup a Flask app inside ShinyProxy. The information in this blog was very helpful: https://dlukes.github.io/flask-wsgi-url-prefix.html

If you are using ShinyProxy 2.5.0, you can add the following code to your `app.py`:

```python
@app.context_processor
def prefix_url_for():
    prefix = ""
    if "SHINYPROXY_PUBLIC_PATH" in os.environ:
        prefix = os.environ["SHINYPROXY_PUBLIC_PATH"]
    def func(url, **args):
        res = url_for(url, **args)
        if res[0] == '/':
            res = prefix + res[1:]
        return res
    return dict(prefix_url_for=func)
```

Then every time you refer to a static file in your templates, you have to use:

```bash
<img src="{{ prefix_url_for('static', filename='myfile.jpg') }}">
<script src={{ prefix_url_for('static', filename='myscript.js") }}">
```

Also every time you make a link to another page in your app, you have to use:

```bash
<a href={{ prefix_url_for('about') }} >About</a>
```

In the upcoming version of ShinyProxy we made some improvements, that should make the support for Flask applications easier, so that this work-around is no longer needed.

**Comment by LEDfan** [comment]
Hi

We created a repo demonstrating how to run a Flask app in the upcoming version of ShinyProxy: https://github.com/openanalytics/shinyproxy-flask-demo

As I believe this question is answered, I'm closing this issue. Feel free to re-open it if you need more help.

**Comment by joakibo** [comment]
Reporting back that the code suggested in https://github.com/openanalytics/shinyproxy/issues/279#issuecomment-875337535 works, but what was supposed to work ShinyProxy > 2.6.0 does not work.
