### ISSUE TITLE
Keycloak group in shiny app

### ISSUE THREAD

**Issue by shosaco** [openanalytics/shinyproxy#299]
Dear all,

I am using Shinyproxy with Keycloak authentification which is working fine. I know how to see the Keycloak Client Role in my Shiny app (using `Sys.getenv("SHINYPROXY_GROUP")`) - but is it possible to see the **Keycloak Group** (not the Keykloak client rule) for a user? 

That would enable more fine-grained data-filtering and authentication methods.

Best regards
sandro

**Comment by dseynaev** [comment]
Hi @shosaco 

you could try connecting to keycloak via the OIDC (`openid`) backend instead of the `keycloak` one.

Then, you can use a custom claim for the shinyproxy group membership: https://shinyproxy.io/documentation/configuration/#group-based-authorization

In keycloak, you would then use a client mapper to map the group membership to that claim

Best,
Daan

**Comment by LEDfan** [comment]
Hi @shosaco

As I believe that your question is answered, I'm closing this issue. Feel free to re-open it if you need more help.
