### ISSUE TITLE
No support for bookmarking

### ISSUE THREAD

**Issue by nlarusstone** [openanalytics/shinyproxy#300]
Following up from the comment here: https://support.openanalytics.eu/t/shiny-bookmarking-the-state-in-url/394/10 about creating a Github issue.

Basically, Shiny Proxy doesn't respect Shiny's bookmarking (apparently because it's running the Shiny app in an iframe...). That means something like:
```r
  onBookmarked(function(url) {
    updateQueryString(url)
  })
```

Works if you run the app directly, but doesn't change the URL when deployed via Shiny Proxy.

This is a big issue for me, as my app uses bookmarking quite heavily.

**Comment by LEDfan** [comment]
Hi thanks for opening this interesting feature, I see the great value of this request.
I investigated the technical aspects of this a bit and I believe we should be able to implement a solution for this.
However, I cannot make any promises when we will be able to do this and in which release it will be included. 

In order to test the implementation (and to make sure it fits your use-case) it would be useful if you could provide an example app that uses this functionality. It can be very simple of course, just a stripped-down version that exposes the behavior you are looking for. Thanks!

**Comment by nlarusstone** [comment]
Great, thanks for the response! I'll leave a demo app below. One note for other people finding this issue is that I was able to work around it by adding a custom JS file to my shiny app:

```javascript
Shiny.addCustomMessageHandler('updateURL', function(message) {
    window.parent.history.replaceState(null, null, message);
});
```
and the corresponding call in my Shiny app:
```r
session$sendCustomMessage("updateURL", message = url)
```

I could then see bookmark params in the URL when I navigated to `<domain>.com/app_direct/<application>`

**Comment by LEDfan** [comment]
Thanks for the example and the workaround. It's interesting to know there is a way to handle it in Shiny. Nevertheless we strive to make ShinyProxy work as seamlessly as possible, so we will still look into a built-in solution sometime.

**Comment by LEDfan** [comment]
Hi, I'm happy to announce that ShinyProxy 3.0.0 supports Shiny Bookmarking! See the [option in the docs](https://shinyproxy.io/documentation/configuration/#track-app-url).
