### ISSUE TITLE
Multiple pods opened in Iframe

### ISSUE THREAD

**Issue by markwsac** [openanalytics/shinyproxy#305]
Thanks for your great open source service in data science community.

I have multiple shiny apps running in shinyproxy framework. I am trying to embed shinyproxy URL in the other static app (run by IT team) via Iframe. When one user visits the link it opens more than 10 containers (should be ideally 2 one for shinyproxy and shiny app). I tested on both docker compose and kubernete based deployment. In kubernete it opens more than 10 pods. This issue exists in both the deployments. It also returns 404 error of JS and CSS resources.

I tried this solution but didn't work - 
https://github.com/openanalytics/shinyproxy/issues/142

I also tried this in ingress but no success - 
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket

Mostly errors are
"Refused to apply style from because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled"

**Comment by LEDfan** [comment]
Hi

I think the issue is that every request in the iframe (e.g. for css, js, .. files) ShinyProxy is starting a new container. This could be caused because ShinyProxy is identifying every request as a different user. I suspect some isolation or misconfiguration of cookies could cause this. You could try the following to debug the issue:

- open the network tab of your browser (a.k.a developer tools)
- open the application
- check which requests are preformed and have a look at which cookies are sent. If every request has a different value for the session cookie, this is the cause of the issue.
- check the console tab for any error or warnings relating to cookies (e.g. sameSite policy, secure flag etc).

**Comment by LEDfan** [comment]
Hi @markwsac 

After thinking about this a bit more, I think I know the cause of this issue. ShinyProxy 2.5.0 sends a session cookie to the browser without a same site cookie policy. Modern browsers are blocking these kind of cookies in a third-party context. (to be precise, browsers are treating them as cookies with a Lax policy). Therefore ShinyProxy is unable to identify a session for each of the requests and thus starts a new container for each request. 

The solution is to change the same site cookie policy to `None` and to enable secure cookies. Unfortunately it is not yet possible to change this policy in ShinyProxy 2.5.0 (unless you are using Redis for session persistence). The good news is that in the next version of ShinyProxy this will be possible. 
You can already start using a snapshot of the next release by using the [docker container](https://hub.docker.com/r/openanalytics/shinyproxy-snapshot/tags?page=1&ordering=last_updated)  (use 2.6.0-SNAPSHOT-20210730.120255 tag)or [the jar](https://nexus.openanalytics.eu/repository/snapshots/eu/openanalytics/shinyproxy/2.6.0-SNAPSHOT/shinyproxy-2.6.0-20210730.120255-10.jar). You then need to use the following config:

```yaml
server:
   secure-cookies: true

proxy:
  same-site-cookie: None 
```

Note that this will only work if you access ShinyProxy using a HTTPS connection. Otherwise some browsers will block the cookies again.
