### ISSUE TITLE
proper configuration of access-groups via keycloak

### ISSUE THREAD

**Issue by panoptikum** [openanalytics/shinyproxy#313]
Dear Folks,

Thanks again for this great tool. I really enjoy working with shinyproxy.

I've got a setup where the authentication runs via keycloak, but I had no luck so far to define the access-groups with group memberships that should come from keycloak. I'm new to use keycloack based authentication. It might be that I do not fully understand how it works. Is it possible to specfiy access-groups while using only keycloak or do I have to use OIDC for that? I want to realize an access restriction per app based on group membership. The authentication already works, but if I set a group restriction, the app vanishes.

Any hint is much appreciated.

Best

**Comment by Dusan-Dingarac** [comment]
Hi Panoptikum,

Keycloak groups you can use just to group deiifernt users at your Keycloak. But to use Keycloak to define Shinyproxy access rights (groups) you need roles. For your realm define role for client which you create for shinyproxy.  That role you give to users (or to Keycloak group for easier user mgm). That role name will appear in Shinyproxy as access-group but also as enviroment variable SHINYPROXY_USERGROUPS but you have to add to application.yml file in Keycloak section 'use-resource-role-mappings: true' (so you can also use it from your R application).

There is some more details about Keycloak and Shinyproxy but only if you need closer connection so that you need more info from Keycloak from your R apps...

**Comment by panoptikum** [comment]
Hi Dusan,

I'm not sure whether I have understood you correctly. We have several groups/teams in our company like:

Team A
Team B
Team C
...
Team Z

There is already a claim for this in our identity management. Then I will have several apps like:

App 1
App 2
...
App 10

Now I want for example the following access rights:
App 1: Team A, Team B
App 10: Team C, Team F, Team Z

If I only define one role to which I add users then I can only grant access to shinyproxy in general but not on a per-app basis. Is that correct or am I missing something?

**Comment by Dusan-Dingarac** [comment]
For your case, you need to create one client role per app. And then to assign that role to teams.
Client role eg. role_app_1, role_app_2....
And for groups Team A and Team B assign role_app_1

And in application.yml for App 1 put:
access-groups: [role_app_1]

I think that would be your setup and later with joining or removing users from group (Team X) in Keycloak you can control access to apps in Shinyproxy.

**Comment by panoptikum** [comment]
This is not an option for me as I do not want to maintain such roles in coexistence with our existing groups that are widely used across the comapny. I'm now using OIDC directly where I can use the already existing claim that returns me an array with all group memberships. It seems to work well. I'm new to the world of authorization providers, but as I understand keycloak is based on top of OIDC. In my case this eventually means the user experience is no different to keycloak.
