### ISSUE TITLE
Change in heartbeat behaviour (v2.6.0)

### ISSUE THREAD

**Issue by nik-humphries** [openanalytics/shinyproxy#340]
In v2.5.0, I was timing out user sessions in app by executing a `session.close()` (We have created a package based off a stackoverflow answer that does it here - https://github.com/grddavies/idler).

Previously when this happened, the heartbeats would stop, even if the browser window was still open which would cause the container to be destroyed after 1 minute (users often just leave their browsers open forever..). But I think due to the new startheartbeats function (for the websocket reconnect? )(https://github.com/openanalytics/shinyproxy/blob/master/src/main/resources/static/js/shiny.connections.js#L30), it will persist these containers that should be removed.

My workaround for this is to source a modified version of https://github.com/openanalytics/shinyproxy/blob/master/src/main/resources/static/js/shiny.app.js commenting out lines 82 and 96.

Funny that this actually kind of contradicts what I want to do with https://github.com/openanalytics/shinyproxy/issues/339 where I actually want the persistence and reconnections!

Do you think allowing the killing of containers that have their session closed but are still open in the browser is a feature you would add, or will the workaround be required forever?

**Comment by LEDfan** [comment]
Hi

If I understand correctly, what you basically want is a way to stop the Shiny app from inside the R session? 
I think the best method is to add a new messageHandler here: https://github.com/grddavies/idler/blob/main/inst/js/idler.js#L1 that listens for a message `stopApp` or something. This handled should then use the following code to stop the app:

```js
Shiny.instances._deleteInstance(Shiny.app.staticState.appInstanceName, function () {
    Shiny.ui.showStoppedPage();
});
```

This gracefully stops the app within ShinyProxy and also shows a nice page indicated to the user that the app was stopped.
You should then trigger this message instead of calling the `session$end` function here https://github.com/grddavies/idler/blob/main/R/idler.R#L33 

Does that work for you?

**Comment by LEDfan** [comment]
Hi , this issue was opened a long time ago and I think that the answer above should do the trick. Therefore, I'm going to close this issue. If you are still facing an issue, please re-open the issue or open a new one.
