### ISSUE TITLE
Change prefix name for Kubernetes pods

### ISSUE THREAD

**Issue by Tazovsky** [openanalytics/shinyproxy#360]
How can I change prefix name for Shinyproxy Kubernetes pods?

Instead of `sp-pod-1b2b8637-0dc9-41fa-a9b2-4e27a4056052` I'd like to have Kubernetes pods named `sp-AAA-1b2b8637-0dc9-41fa-a9b2-4e27a4056052`, `sp-BBB-1b2b8637-0dc9-41fa-a9b2-4e27a4056052`, `sp-CCC-1b2b8637-0dc9-41fa-a9b2-4e27a4056052`.

Current output from `kubectl`:

```
$ kubectl --kubeconfig kubeconfig -n <my namespace>  get pods | grep sp-pod
sp-pod-1b2b8637-0dc9-41fa-a9b2-4e27a4056052   1/1     Running   0          23m
sp-pod-b1f73a81-c02c-4153-b78d-7549fe9f2aed   1/1     Running   0          23m
sp-pod-c0129a9b-6ff4-41dd-8798-e5fa61687b6e   1/1     Running   0          23m
```

**Comment by LEDfan** [comment]
Hi 

This is currently not possible. I'll keep this issue open as a feature request.
Why do you want to change the prefix? Maybe there is already a workaround for what you want to achieve.

**Comment by danielloader** [comment]
To piggy back off this, would be nice to be able to have the `.specs[].id` value in the name somewhere, makes it easier to at a glance see what's happening without needing to inspect the pod image value to see which app is running in that pod.

**Comment by LEDfan** [comment]
Hi @nickmelis 

The id you see in the ShinyProxy, is the id of the `proxy` object. In the `KubernetesBackend` an `UUID` is generated for the containerId and used in the name of the pod (https://github.com/openanalytics/containerproxy/blob/2c71c88a0f8a8f71e2551343e09b659c6f11c1fe/src/main/java/eu/openanalytics/containerproxy/backend/kubernetes/KubernetesBackend.java#L179)

So in order to have custom names, you could modify the `KubernetesBackend` code. However, I think it would make sense to provide a configuration option which uses SpEL to configure the name of the pod. By default this could be something like:

````
sp-pod-#{proxy.getRuntimeValue('SHINYPROXY_PROXY_ID')}-#{container.getRuntimeValue('SHINYPROXY_CONTAINER_INDEX')}
```

**Comment by LEDfan** [comment]
Hi, this is now part of ShinyProxy 3.1.0, which we released today. Thanks again for your suggestion!
