### ISSUE TITLE
Getting kicked out of app to index page

### ISSUE THREAD

**Issue by PlasmaPower** [openanalytics/shinyproxy#45]
We've been having an issue where a user gets kicked out of the app and back to the index page. It's very rare and unfortunately hard to reproduce. However, it might be useful to know that before we deployed #36, upon reentering the app, the user would get the "No Session ID Found" error. If it matters, we're using keycloak for authentication.

Any help narrowing this down, or hints on where to look, would be very much appreciated.

**Comment by PlasmaPower** [comment]
From my testing, a session expiring results in a grey screen. Though heartbeats and app requests do get redirected to `/login`, it does not result in the whole page getting redirected. I'm now even less sure why this happens.

**Comment by fmichielssen** [comment]
Hi @PlasmaPower ,

That is indeed a peculiar issue. There is no script code that causes a window.location change. The only code that may change the page contents, is in app.html that shows an error message when an app fails to open, but I think that is not the culprit here.

Is there any relevant information in the log file? Or are there any addons installed in the browser that could interfere with the navigation?

**Comment by PlasmaPower** [comment]
It's occurred on two different computers, one Chrome, one Firefox. Unfortunately I don't have logs from the time.

The only thing I can think of is the `document.open` call for the error message, but that should only happen once and the iframe wouldn't have loaded.

**Comment by LEDfan** [comment]
This is quite an old issue and in the meantime we never had (AFAIK) a similar issue. Therefore I'm closing this issue. Feel free to re-open it if you need more help.
