### ISSUE TITLE
[Feature request] JDBC authentication

### ISSUE THREAD

**Issue by gbisschoff** [openanalytics/shinyproxy#49]
Hi ,

I think implementing a JDBC authentication method with common database back ends (postgres, mysql, ...) is a good idea. 

Thanks so much for all you hard work. I really like what you are doing.

**Comment by zagorulkinde** [comment]
@gbisschoff i'm currently working on it. I will push PR in about few days.

**Comment by LEDfan** [comment]
Hi,

This is quite an old issue. I'm also not sure what you are exactly requesting, since ShinyProxy does not directly connect to a database (unless for the [usage statics](https://shinyproxy.io/documentation/usage-statistics/) feature, which support auth).  Therefore, I'm closing this issue. If you encounter any issue or need help feel free to open a new issue!
