### ISSUE TITLE
Example of using external-url

### ISSUE THREAD

**Issue by danielloader** [openanalytics/shinyproxy#491]
Excitedly been watching the released notifications for 3.1.0 and this feature has turned up, but I don't know how to use it, so a simple example would be appreciated!

Thanks

**Comment by LEDfan** [comment]
Thanks for your additional testing, are you perhaps using custom templates? The idea of the external url feature is that the link on the main page redirects the user to the external url. In order for this to work, you'll need to use the templates that come with ShinyProxy 3.1.0. 

If you open the app url of the external app, you'll indeed get an error, because there is no way to start an external app. But maybe it makes sense here to also redirect the user to the external URL.

**Comment by danielloader** [comment]
So it's not expected to embed it inside the iframe/application, it's just a static link that the browser goes to wholesale?

**Comment by LEDfan** [comment]
Hi, we just released ShinyProxy 3.1.1, when you now visit the page of an app that is using the `external-url` property, you'll be redirected to this url. So this will not yet include the app as an iframe or proxy the app. If you still find this important, feel free to open a new issue for this.
