### ISSUE TITLE
Continuous Deployment with Shiny Proxy

### ISSUE THREAD

**Issue by adamrobinson361** [openanalytics/shinyproxy#68]
Thanks for this tool - looks like a really great open source edition to deploying shiny apps in a scalable way!

Having gone through the docs I can't see anything on how continuous deployment would work with shiny proxy. 

My question is say you have a server with 3 apps up and running and you want to update an app or publish a new app is there a way to do this without stopping the service, updating the yml and restarting it?

I tried updating the application.yml on a running instance but this didn't do anything (as expected). Is there a way to update it whilst its up?

**Comment by shrektan** [comment]
update the app should basically no problem I guess because that's how shiny itself works. However, publishing a new app w/o interrupting is in doubt. I remember that shinyproxy do not support ad-hoc reloading the application.yml. 

Well, I'm not the expert. Welcome to correct me...

**Comment by hejatibor** [comment]
No, it's not possible with this release:
https://support.openanalytics.eu/t/adding-new-applications-without-restarting-shinyproxy/200

**Comment by shrektan** [comment]
You’re right. I forgot the app in shinyproxy is bundle into the docket image. It’s the shinyserver that can update / add the apps in real-time.

**Comment by fmichielssen** [comment]
Updating an app is indeed possible without downtime, by building a new docker image. ShinyProxy will automatically use the latest image build, unless you specify an image version in your yml.

Adding new apps is not possible, however, because reloading the yml at runtime is a tricky concept. It makes sense for the `apps` section, but other config is not straightforward to re-apply; e.g. the authentication-related sections.

That being said, we are trying to add more flexibility in this regard in the next major release of ShinyProxy. There will be support for runtime parameters, such as the amount of RAM a proxy is allowed to use. It will also be possible to launch a custom app spec, but the details of this have not yet been drawn out.

**Comment by adamrobinson361** [comment]
Thanks for all the replies. Good to know that building new docker image updates an existing app and the current difficulties in updating yml on the fly. Look forward to the next major release!
