### ISSUE TITLE
openID logout

### ISSUE THREAD

**Issue by gbisschoff** [openanalytics/shinyproxy#87]
Hi,

I've been playing around with the latest master version (2.0.2) and found that when you authenticate using the openID connector that you cant actually logout. 

In the log it does show that the user has logged out, but the user does not get redirected to the login page again.

**Comment by fmichielssen** [comment]
Hi @gbisschoff ,

Do you mean that the user goes straight back to the app list page, instead of a login page?

There is indeed the issue that the shinyproxy `/logout` invalidates the session locally, but not on the openid provider level. So when the user logs out, they get redirected to the openid login page, which immediately authenticates again and redirects back to the shinyproxy app listing page.

A fix has been committed in develop: https://github.com/openanalytics/containerproxy/commit/f5c1a4f7020a02caa07ad9425bca409ac13ce359
which allows you to specify a `logout-url` to invalidate the session on the openid provider level.

**Comment by gbisschoff** [comment]
Yes, exactly. 

Thanks so much for the reply. 
_Closing as it has already been addressed._
