### ISSUE TITLE
Feature request: Per app option for spare docker containers

### ISSUE THREAD

**Issue by wligtenberg** [openanalytics/shinyproxy#89]
We have a couple of application that take a while to launch. It would be great to have a configuration option to have a couple of docker containers waiting for users. This would greatly reduce the time before the user can use the application.

I am open for hints on how to tackle the problem and willing to help out.

**Comment by fmichielssen** [comment]
Hi Willem,

I think it's a good idea to think about how these loading times can be reduced or eliminated.
Here are some of my thoughts about this:

- Setting up a 'generic' container pool is problematic, because each container is specific to one app and one user (some variables are injected, such as the SHINYPROXY_USERNAME env var)

- Instead, it might be safer to spawn one or several containers when the user logs in. E.g. for a 'heavy' app that you expect the user will access after login.

- However in this case there is less time between the user logging in and accessing the app.

- There must be some way to ensure these pre-launched containers do not get killed by the heartbeat mechanism, that automatically shuts down idle containers.

**Comment by wligtenberg** [comment]
Hi Frederick,

We should be able inject those using docker exec at a later time point as well.
In that way, we could have unassigned container waiting for users. Because I think spawning containers after a user has logged in is already too late.

Then there is the issue of the heartbeat. We could have a process that will perform a heart beat as long as the user value is not yet set. In this way, as soon as the user is assigned, the normal heartbeat mechanism is activated.

**Comment by MartinRoth** [comment]
Hi,

we have the same issue. Loading some containers at login would be already quite an improvement. Is there already a way how to do this? Can we do something to help make this possible?

Cheers,
Martin

**Comment by thomasthomasth** [comment]
Since the Shiny environment is mostly designed for Analytical purposes, the developers are supposed to have a relatively slow number of Applications here. Lets say there are 20 Apps and 1000 users out there.

A potential solution to shrink the loading time would be that when a user logs in, then in a single container 20 applications should be launched immediately in the backgroud and exposed to 20 different ports within this single image. Once the user chooses the appropriate application, the port shold be forwarded. In case the ShinyProxy environment is designed for a large number of Applications, then there should be an option what Apps should be launched whenever a user logs in. When the user logs out / no user activity recorded in an App then the container can be shut down.

The reason why it would be crucial to specify what application should not be started immediately is that there are many cases when a DB query runs for a longer period of time. However, in all other cases, when you read small datasets from some in-memory Database, it should be superfast. And the Developers of any Shiny Application should be aware of how much it takes to load an App. And if there are DB connections, then we should be able to configure our DB - how many connections can be set up at once.

I think this poses

**Comment by michaelhogersosis** [comment]
Hi all, 

We are using a Kubernetes backend and managed to reach a 5-10 second start time. Fortunately the application was build on top of ShinyProxy from an early stage so we have a relatively optimal setup (I think). What is the minimum one should be able to reach @fmichielssen? Also, should one expect a significant difference in load times between setting proxy.kubernetes.image-pull-policy to Always or IfNotPresent? 

We received a few internal comments stating that the initial start time can be a bit lengthy at times, it is fine at the moment though, but being able to initialise containers in order to reach a 1-2 second start time would be great as it further diminishes differences between web applications written with R Shiny and other frameworks!

**Comment by tblazina** [comment]
We are facing the similar issue - average 5-10 second startup time for users and when users reload the app they get a blank page because the app is being restarted (i.e. the pod receives 'Completed' status, and then restarts), and has to wait until the pod is restarted before being able to access the app.

**Comment by LEDfan** [comment]
Hi, this is now part of ShinyProxy 3.1.0, which we released today. We hope you enjoy this feature!
